### PR TITLE
SimpleTemplateMatching -- make matcher public

### PR DESCRIPTION
**Pull request by jeremydouglass**
This is the simplest possible change to make template matching usable by exposing scores.

### CODE REVIEW

**Comment by jeremydouglass** [comment]
This addresses but wouldn't fully resolve #5.

Even better would be an (additional) an interface to those results, as a returned TemplateMatching with a getter, and/or a simplified method like `scores()` rather than .matcher.getResults() -- something that returned the results in a much Processing-friendlier format than a `FastQueue<Match>`.

**Comment by lessthanoptimal** [comment]
it certainly is a simple approach! I'll take a look at doing it a bit cleaner when I update the wrapper for the latest stable release.

**Comment by jeremydouglass** [comment]
I'd be happy to draft PR a getter and/or scores interface for [Match](https://github.com/lessthanoptimal/BoofCV/blob/SNAPSHOT/main/boofcv-feature/src/main/java/boofcv/struct/feature/Match.java) if you have ideas about what direction you would prefer. I'm assuming that it would involve returning the [FastQueue](http://ddogleg.org/javadoc/org/ddogleg/struct/FastQueue.html) contents as either a Match[] with FastQueue.getData() or even as a PVector[] with values x, y, z=score. The key think would be changing the score from double to float -- assuming that wouldn't cause a problem for the scoring algorithms.

Context: I just saw template matching projects on the forum recently and was trying to offer a quick change that would allow them to move forward using BoofCV.

https://discourse.processing.org/t/help-reading-data-from-a-game-diablo-ii-or-analyzing-an-image-from-it-for-text-recognition/21782/4?u=jeremydouglass

**Comment by lessthanoptimal** [comment]
I just got the code to build again with the latest stable release. I think it should be possible to get a new version quickly and provide access to this new feature.

Maybe return boofcv.struct.feature.Match instead of trying to simplify this too much?

**Comment by jeremydouglass** [comment]
Sure, returning Match seems just fine. Double to float isn't a huge deal.

**Comment by jeremydouglass** [comment]
Just to confirm -- did you want to close this and do your own commit resolving #5, or were you asking me to make a new PR on SNAPSHOT that returns Match?

**Comment by lessthanoptimal** [comment]
I'll do my own change and post here so you can take a look at it.

**Comment by lessthanoptimal** [comment]
testing the example code and ran into this problem again. https://github.com/processing/processing-video/issues/136  I think Video in linux has been broken for years. Looks like it might get fix this year.

**Comment by lessthanoptimal** [comment]
@jeremydouglass SNAPSHOT has the changes if you want to test. I'll update tomorrow unless some problems are found.

**Comment by jeremydouglass** [comment]
I haven't built and tested, just read the SNAPSHOT commits, but exposing Match through SimpleTemplateMatching.detect() looks good, and the minimal changes to the example are very clean.

I also noticed an added method SimpleTrackerPoints.getTrackAge -- seems unrelated to the rest of the commit (?), but I am assuming not a problem / mistake.

https://github.com/lessthanoptimal/BoofProcessing/commit/96f5bd3fff85dd5da9084898972baabc25e70e6b#diff-c51167e6b99a084c638b50cbe5a8f4cfR87

**Comment by lessthanoptimal** [comment]
yeah that was on purpose. thought someone might find it useful and being informal about keeping each commit to one task. thanks for looking!

**Comment by lessthanoptimal** [comment]
Updated the new .zip. I'll close this ticket when it's verified that Processing has noticed the new version.

**Comment by lessthanoptimal** [comment]
It's been updated.

**Pull request closed without merging**
